services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./backend:/app
    networks:
      - minha-rede
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge